name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /var/www
            if [ -d "lurniva_dashboard" ]; then
              rm -rf lurniva_dashboard
            fi
            git clone git@github.com:Engrkhizarkhan/lurniva_dashboard.git
            cd lurniva_dashboard/sql
            mysql -u root -p${{ secrets.DB_PASSWORD }} lurnivaDB < lurnivaDB.sql
            systemctl reload php7.4-fpm
            systemctl reload nginx
