name: Deploy to Lurniva VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: LurnivaVM
          key: ${{ secrets.VM_KEY }}
          script: |
            cd /var/www/lurniva_dashboard
            git pull origin main
            sudo chown -R www-data:www-data /var/www/lurniva_dashboard
            ./deploy_migrations.sh
            sudo systemctl reload php8.1-fpm
            sudo systemctl reload nginx
            echo "Deployment to Lurniva VM completed."