name: Deploy to Lurniva VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: LurnivaVM
          key: ${{ secrets.VM_KEY }}
                    # ./deploy_migrations.sh
          script: | # mysql -u lurnivauser -p'lurnivaDBPassword' lurnivaDB < /var/www/lurniva_dashboard/sql/lurnivaDB.sql >> This is the script to add database table using Ci/CD
            script: |
                  cd /var/www/lurniva_dashboard

                  # 1. Make sure LurnivaVM owns the repo so Git can run
                  sudo chown -R LurnivaVM:LurnivaVM /var/www/lurniva_dashboard

                  # 2. Allow Git in this directory
                  git config --global --add safe.directory /var/www/lurniva_dashboard

                  # 3. Force update the code from GitHub
                  git fetch origin main
                  git reset --hard origin/main
                  git clean -fd

                  # 4. Set ownership for the web server
                  sudo chown -R www-data:www-data /var/www/lurniva_dashboard

                  # 5. Reload PHP and Nginx services
                  sudo systemctl restart php8.3-fpm
                  sudo systemctl reload nginx

                  # 6. Confirm deployment
                  echo "Deployment to Lurniva VM completed successfully."

 