name: Deploy PHP App

on:
  push:
    branches:
      - main

#deployment....

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            export GIT_SSH_COMMAND='ssh -i /home/LurnivaVM/.ssh/id_ed25519 -o StrictHostKeyChecking=no'
            bash /var/www/deploy.sh
